complete -c ufp -f
complete -c ufp -s h -d 'Help'
complete -c ufp -s i -d 'Install'
complete -c ufp -s r -d 'Remove'
complete -c ufp -s e -d 'Reinstall'
complete -c ufp -s f -d 'Refresh & Install'
complete -c ufp -s q -d 'Query package info'
complete -c ufp -s c -d 'Clean orphans/cache'
complete -c ufp -s s -d 'Search'
complete -c ufp -s b -d 'Rollback (Fedora)'
complete -c ufp -s u -d 'Full system upgrade'
complete -c ufp -s v -d 'Show version'
complete -c ufp -s m -d 'Upgrade firmware'
complete -c ufp -s g -d 'Update Ghostty'
